//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022-2023 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeWatcher) DeepCopyInto(out *EdgeWatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeWatcher.
func (in *EdgeWatcher) DeepCopy() *EdgeWatcher {
	if in == nil {
		return nil
	}
	out := new(EdgeWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchRequest) DeepCopyInto(out *WatchRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchRequest.
func (in *WatchRequest) DeepCopy() *WatchRequest {
	if in == nil {
		return nil
	}
	out := new(WatchRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchRequestStatus) DeepCopyInto(out *WatchRequestStatus) {
	*out = *in
	out.WatchRequest = in.WatchRequest
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchRequestStatus.
func (in *WatchRequestStatus) DeepCopy() *WatchRequestStatus {
	if in == nil {
		return nil
	}
	out := new(WatchRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatcherAgent) DeepCopyInto(out *WatcherAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatcherAgent.
func (in *WatcherAgent) DeepCopy() *WatcherAgent {
	if in == nil {
		return nil
	}
	out := new(WatcherAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WatcherAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatcherAgentList) DeepCopyInto(out *WatcherAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WatcherAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatcherAgentList.
func (in *WatcherAgentList) DeepCopy() *WatcherAgentList {
	if in == nil {
		return nil
	}
	out := new(WatcherAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WatcherAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatcherAgentSpec) DeepCopyInto(out *WatcherAgentSpec) {
	*out = *in
	in.ResyncTimestamp.DeepCopyInto(&out.ResyncTimestamp)
	out.EdgeWatcher = in.EdgeWatcher
	if in.WatchRequests != nil {
		in, out := &in.WatchRequests, &out.WatchRequests
		*out = make([]WatchRequest, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatcherAgentSpec.
func (in *WatcherAgentSpec) DeepCopy() *WatcherAgentSpec {
	if in == nil {
		return nil
	}
	out := new(WatcherAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatcherAgentStatus) DeepCopyInto(out *WatcherAgentStatus) {
	*out = *in
	in.ResyncTimestamp.DeepCopyInto(&out.ResyncTimestamp)
	if in.WatchRequests != nil {
		in, out := &in.WatchRequests, &out.WatchRequests
		*out = make([]WatchRequestStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatcherAgentStatus.
func (in *WatcherAgentStatus) DeepCopy() *WatcherAgentStatus {
	if in == nil {
		return nil
	}
	out := new(WatcherAgentStatus)
	in.DeepCopyInto(out)
	return out
}
